version: '3'
services:    
    balneabilidade:
        build: ./
        restart: always
        networks:
            - balneabilidade   
        environment:
            - LISTEN_PORT=8080     
        ports:            
            - "0.0.0.0:8080:8080"            
        volumes:            
            - ./app:/app:rw 
networks:
    balneabilidade:
        driver: bridge
