version: '3'
services:    
    balneabilidade:
        build: ./
        restart: always
        networks:
            - balneabilidade   
        environment:           
            - FLASK_APP=main.py
            - FLASK_DEBUG=1
            - 'RUN=flask run --host=0.0.0.0 --port=8080'
        command: flask run --host=0.0.0.0 --port=8080 
        ports:            
            - "0.0.0.0:8080:8080"            
        volumes:            
            - ./app:/app:rw 
networks:
    balneabilidade:
        driver: bridge
